package diu.edu.bd;
// Generated Jun 4, 2016 8:48:36 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Picutting generated by hbm2java
 */
public class Picutting  implements java.io.Serializable {


     private int picuttingSerial;
     private Date cuttingDate;
     private Integer planCuttingProduction;
     private Integer actualCuttingProduction;
     private Integer totalWorkingDay;
     private Integer averageWorkinghourCutting;
     private Integer cuttingTotalManPower;
     private Integer totalNoOfManHourAvailableCutting;

    public Picutting() {
    }

	
    public Picutting(int picuttingSerial) {
        this.picuttingSerial = picuttingSerial;
    }
    public Picutting(int picuttingSerial, Date cuttingDate, Integer planCuttingProduction, Integer actualCuttingProduction, Integer totalWorkingDay, Integer averageWorkinghourCutting, Integer cuttingTotalManPower, Integer totalNoOfManHourAvailableCutting) {
       this.picuttingSerial = picuttingSerial;
       this.cuttingDate = cuttingDate;
       this.planCuttingProduction = planCuttingProduction;
       this.actualCuttingProduction = actualCuttingProduction;
       this.totalWorkingDay = totalWorkingDay;
       this.averageWorkinghourCutting = averageWorkinghourCutting;
       this.cuttingTotalManPower = cuttingTotalManPower;
       this.totalNoOfManHourAvailableCutting = totalNoOfManHourAvailableCutting;
    }
   
    public int getPicuttingSerial() {
        return this.picuttingSerial;
    }
    
    public void setPicuttingSerial(int picuttingSerial) {
        this.picuttingSerial = picuttingSerial;
    }
    public Date getCuttingDate() {
        return this.cuttingDate;
    }
    
    public void setCuttingDate(Date cuttingDate) {
        this.cuttingDate = cuttingDate;
    }
    public Integer getPlanCuttingProduction() {
        return this.planCuttingProduction;
    }
    
    public void setPlanCuttingProduction(Integer planCuttingProduction) {
        this.planCuttingProduction = planCuttingProduction;
    }
    public Integer getActualCuttingProduction() {
        return this.actualCuttingProduction;
    }
    
    public void setActualCuttingProduction(Integer actualCuttingProduction) {
        this.actualCuttingProduction = actualCuttingProduction;
    }
    public Integer getTotalWorkingDay() {
        return this.totalWorkingDay;
    }
    
    public void setTotalWorkingDay(Integer totalWorkingDay) {
        this.totalWorkingDay = totalWorkingDay;
    }
    public Integer getAverageWorkinghourCutting() {
        return this.averageWorkinghourCutting;
    }
    
    public void setAverageWorkinghourCutting(Integer averageWorkinghourCutting) {
        this.averageWorkinghourCutting = averageWorkinghourCutting;
    }
    public Integer getCuttingTotalManPower() {
        return this.cuttingTotalManPower;
    }
    
    public void setCuttingTotalManPower(Integer cuttingTotalManPower) {
        this.cuttingTotalManPower = cuttingTotalManPower;
    }
    public Integer getTotalNoOfManHourAvailableCutting() {
        return this.totalNoOfManHourAvailableCutting;
    }
    
    public void setTotalNoOfManHourAvailableCutting(Integer totalNoOfManHourAvailableCutting) {
        this.totalNoOfManHourAvailableCutting = totalNoOfManHourAvailableCutting;
    }




}


