package diu.edu.bd;
// Generated Jun 4, 2016 8:48:36 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pifinishing generated by hbm2java
 */
public class Pifinishing  implements java.io.Serializable {


     private int pifinishingSerial;
     private Date finishingDate;
     private Integer planFinishingProduction;
     private Integer actualFinishingProduction;
     private Integer totalWorkingDay;
     private Integer averageWorkinghourFinishing;
     private Integer finishingTotalManPower;
     private Integer totalNoOfManHourAvailableFinishing;

    public Pifinishing() {
    }

	
    public Pifinishing(int pifinishingSerial) {
        this.pifinishingSerial = pifinishingSerial;
    }
    public Pifinishing(int pifinishingSerial, Date finishingDate, Integer planFinishingProduction, Integer actualFinishingProduction, Integer totalWorkingDay, Integer averageWorkinghourFinishing, Integer finishingTotalManPower, Integer totalNoOfManHourAvailableFinishing) {
       this.pifinishingSerial = pifinishingSerial;
       this.finishingDate = finishingDate;
       this.planFinishingProduction = planFinishingProduction;
       this.actualFinishingProduction = actualFinishingProduction;
       this.totalWorkingDay = totalWorkingDay;
       this.averageWorkinghourFinishing = averageWorkinghourFinishing;
       this.finishingTotalManPower = finishingTotalManPower;
       this.totalNoOfManHourAvailableFinishing = totalNoOfManHourAvailableFinishing;
    }
   
    public int getPifinishingSerial() {
        return this.pifinishingSerial;
    }
    
    public void setPifinishingSerial(int pifinishingSerial) {
        this.pifinishingSerial = pifinishingSerial;
    }
    public Date getFinishingDate() {
        return this.finishingDate;
    }
    
    public void setFinishingDate(Date finishingDate) {
        this.finishingDate = finishingDate;
    }
    public Integer getPlanFinishingProduction() {
        return this.planFinishingProduction;
    }
    
    public void setPlanFinishingProduction(Integer planFinishingProduction) {
        this.planFinishingProduction = planFinishingProduction;
    }
    public Integer getActualFinishingProduction() {
        return this.actualFinishingProduction;
    }
    
    public void setActualFinishingProduction(Integer actualFinishingProduction) {
        this.actualFinishingProduction = actualFinishingProduction;
    }
    public Integer getTotalWorkingDay() {
        return this.totalWorkingDay;
    }
    
    public void setTotalWorkingDay(Integer totalWorkingDay) {
        this.totalWorkingDay = totalWorkingDay;
    }
    public Integer getAverageWorkinghourFinishing() {
        return this.averageWorkinghourFinishing;
    }
    
    public void setAverageWorkinghourFinishing(Integer averageWorkinghourFinishing) {
        this.averageWorkinghourFinishing = averageWorkinghourFinishing;
    }
    public Integer getFinishingTotalManPower() {
        return this.finishingTotalManPower;
    }
    
    public void setFinishingTotalManPower(Integer finishingTotalManPower) {
        this.finishingTotalManPower = finishingTotalManPower;
    }
    public Integer getTotalNoOfManHourAvailableFinishing() {
        return this.totalNoOfManHourAvailableFinishing;
    }
    
    public void setTotalNoOfManHourAvailableFinishing(Integer totalNoOfManHourAvailableFinishing) {
        this.totalNoOfManHourAvailableFinishing = totalNoOfManHourAvailableFinishing;
    }




}


