package diu.edu.bd;
// Generated Jun 4, 2016 8:48:36 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pimanpower generated by hbm2java
 */
public class Pimanpower  implements java.io.Serializable {


     private int pimanPowerSerial;
     private Date date;
     private Integer sweingOperatorPresent;
     private Integer sweingHelperPresent;
     private Integer sweingOperatorHelperPresent;
     private Integer cuttingTotalManPower;
     private Integer finishingTotalManPower;
     private Integer factoryTotalManPower;
     private Integer totalNoOfManHourAvilableMohel;
     private Integer totalNoOfManHourAvailableCutting;
     private Integer totalNoOfManHourAvailableFinishing;
     private Integer totalNoOfManHourAvailableFactory;

    public Pimanpower() {
    }

	
    public Pimanpower(int pimanPowerSerial) {
        this.pimanPowerSerial = pimanPowerSerial;
    }
    public Pimanpower(int pimanPowerSerial, Date date, Integer sweingOperatorPresent, Integer sweingHelperPresent, Integer sweingOperatorHelperPresent, Integer cuttingTotalManPower, Integer finishingTotalManPower, Integer factoryTotalManPower, Integer totalNoOfManHourAvilableMohel, Integer totalNoOfManHourAvailableCutting, Integer totalNoOfManHourAvailableFinishing, Integer totalNoOfManHourAvailableFactory) {
       this.pimanPowerSerial = pimanPowerSerial;
       this.date = date;
       this.sweingOperatorPresent = sweingOperatorPresent;
       this.sweingHelperPresent = sweingHelperPresent;
       this.sweingOperatorHelperPresent = sweingOperatorHelperPresent;
       this.cuttingTotalManPower = cuttingTotalManPower;
       this.finishingTotalManPower = finishingTotalManPower;
       this.factoryTotalManPower = factoryTotalManPower;
       this.totalNoOfManHourAvilableMohel = totalNoOfManHourAvilableMohel;
       this.totalNoOfManHourAvailableCutting = totalNoOfManHourAvailableCutting;
       this.totalNoOfManHourAvailableFinishing = totalNoOfManHourAvailableFinishing;
       this.totalNoOfManHourAvailableFactory = totalNoOfManHourAvailableFactory;
    }
   
    public int getPimanPowerSerial() {
        return this.pimanPowerSerial;
    }
    
    public void setPimanPowerSerial(int pimanPowerSerial) {
        this.pimanPowerSerial = pimanPowerSerial;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getSweingOperatorPresent() {
        return this.sweingOperatorPresent;
    }
    
    public void setSweingOperatorPresent(Integer sweingOperatorPresent) {
        this.sweingOperatorPresent = sweingOperatorPresent;
    }
    public Integer getSweingHelperPresent() {
        return this.sweingHelperPresent;
    }
    
    public void setSweingHelperPresent(Integer sweingHelperPresent) {
        this.sweingHelperPresent = sweingHelperPresent;
    }
    public Integer getSweingOperatorHelperPresent() {
        return this.sweingOperatorHelperPresent;
    }
    
    public void setSweingOperatorHelperPresent(Integer sweingOperatorHelperPresent) {
        this.sweingOperatorHelperPresent = sweingOperatorHelperPresent;
    }
    public Integer getCuttingTotalManPower() {
        return this.cuttingTotalManPower;
    }
    
    public void setCuttingTotalManPower(Integer cuttingTotalManPower) {
        this.cuttingTotalManPower = cuttingTotalManPower;
    }
    public Integer getFinishingTotalManPower() {
        return this.finishingTotalManPower;
    }
    
    public void setFinishingTotalManPower(Integer finishingTotalManPower) {
        this.finishingTotalManPower = finishingTotalManPower;
    }
    public Integer getFactoryTotalManPower() {
        return this.factoryTotalManPower;
    }
    
    public void setFactoryTotalManPower(Integer factoryTotalManPower) {
        this.factoryTotalManPower = factoryTotalManPower;
    }
    public Integer getTotalNoOfManHourAvilableMohel() {
        return this.totalNoOfManHourAvilableMohel;
    }
    
    public void setTotalNoOfManHourAvilableMohel(Integer totalNoOfManHourAvilableMohel) {
        this.totalNoOfManHourAvilableMohel = totalNoOfManHourAvilableMohel;
    }
    public Integer getTotalNoOfManHourAvailableCutting() {
        return this.totalNoOfManHourAvailableCutting;
    }
    
    public void setTotalNoOfManHourAvailableCutting(Integer totalNoOfManHourAvailableCutting) {
        this.totalNoOfManHourAvailableCutting = totalNoOfManHourAvailableCutting;
    }
    public Integer getTotalNoOfManHourAvailableFinishing() {
        return this.totalNoOfManHourAvailableFinishing;
    }
    
    public void setTotalNoOfManHourAvailableFinishing(Integer totalNoOfManHourAvailableFinishing) {
        this.totalNoOfManHourAvailableFinishing = totalNoOfManHourAvailableFinishing;
    }
    public Integer getTotalNoOfManHourAvailableFactory() {
        return this.totalNoOfManHourAvailableFactory;
    }
    
    public void setTotalNoOfManHourAvailableFactory(Integer totalNoOfManHourAvailableFactory) {
        this.totalNoOfManHourAvailableFactory = totalNoOfManHourAvailableFactory;
    }




}


