package diu.edu.bd;
// Generated Jun 4, 2016 8:48:36 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pisewing generated by hbm2java
 */
public class Pisewing  implements java.io.Serializable {


     private int pisewingSerial;
     private Date sewingDate;
     private Integer planSewingProduction;
     private Integer actualSewingProduction;
     private Integer noOfLineSewing;
     private Integer noOfLineDaysSewing;
     private Integer noOfLineHoursSewing;
     private Integer totalWorkingDay;
     private Integer averageWorkinghourSewing;
     private Integer monthlyTotalRunningMc;
     private Integer monthlyAverageRunningMc;
     private Integer factoryTotalMc;
     private Integer sewingOperatorPresent;
     private Integer sewingHelperPresent;
     private Integer sewingOperatorHelperPresent;
     private Integer totalNoOfManHourAvilableMohel;

    public Pisewing() {
    }

	
    public Pisewing(int pisewingSerial) {
        this.pisewingSerial = pisewingSerial;
    }
    public Pisewing(int pisewingSerial, Date sewingDate, Integer planSewingProduction, Integer actualSewingProduction, Integer noOfLineSewing, Integer noOfLineDaysSewing, Integer noOfLineHoursSewing, Integer totalWorkingDay, Integer averageWorkinghourSewing, Integer monthlyTotalRunningMc, Integer monthlyAverageRunningMc, Integer factoryTotalMc, Integer sewingOperatorPresent, Integer sewingHelperPresent, Integer sewingOperatorHelperPresent, Integer totalNoOfManHourAvilableMohel) {
       this.pisewingSerial = pisewingSerial;
       this.sewingDate = sewingDate;
       this.planSewingProduction = planSewingProduction;
       this.actualSewingProduction = actualSewingProduction;
       this.noOfLineSewing = noOfLineSewing;
       this.noOfLineDaysSewing = noOfLineDaysSewing;
       this.noOfLineHoursSewing = noOfLineHoursSewing;
       this.totalWorkingDay = totalWorkingDay;
       this.averageWorkinghourSewing = averageWorkinghourSewing;
       this.monthlyTotalRunningMc = monthlyTotalRunningMc;
       this.monthlyAverageRunningMc = monthlyAverageRunningMc;
       this.factoryTotalMc = factoryTotalMc;
       this.sewingOperatorPresent = sewingOperatorPresent;
       this.sewingHelperPresent = sewingHelperPresent;
       this.sewingOperatorHelperPresent = sewingOperatorHelperPresent;
       this.totalNoOfManHourAvilableMohel = totalNoOfManHourAvilableMohel;
    }
   
    public int getPisewingSerial() {
        return this.pisewingSerial;
    }
    
    public void setPisewingSerial(int pisewingSerial) {
        this.pisewingSerial = pisewingSerial;
    }
    public Date getSewingDate() {
        return this.sewingDate;
    }
    
    public void setSewingDate(Date sewingDate) {
        this.sewingDate = sewingDate;
    }
    public Integer getPlanSewingProduction() {
        return this.planSewingProduction;
    }
    
    public void setPlanSewingProduction(Integer planSewingProduction) {
        this.planSewingProduction = planSewingProduction;
    }
    public Integer getActualSewingProduction() {
        return this.actualSewingProduction;
    }
    
    public void setActualSewingProduction(Integer actualSewingProduction) {
        this.actualSewingProduction = actualSewingProduction;
    }
    public Integer getNoOfLineSewing() {
        return this.noOfLineSewing;
    }
    
    public void setNoOfLineSewing(Integer noOfLineSewing) {
        this.noOfLineSewing = noOfLineSewing;
    }
    public Integer getNoOfLineDaysSewing() {
        return this.noOfLineDaysSewing;
    }
    
    public void setNoOfLineDaysSewing(Integer noOfLineDaysSewing) {
        this.noOfLineDaysSewing = noOfLineDaysSewing;
    }
    public Integer getNoOfLineHoursSewing() {
        return this.noOfLineHoursSewing;
    }
    
    public void setNoOfLineHoursSewing(Integer noOfLineHoursSewing) {
        this.noOfLineHoursSewing = noOfLineHoursSewing;
    }
    public Integer getTotalWorkingDay() {
        return this.totalWorkingDay;
    }
    
    public void setTotalWorkingDay(Integer totalWorkingDay) {
        this.totalWorkingDay = totalWorkingDay;
    }
    public Integer getAverageWorkinghourSewing() {
        return this.averageWorkinghourSewing;
    }
    
    public void setAverageWorkinghourSewing(Integer averageWorkinghourSewing) {
        this.averageWorkinghourSewing = averageWorkinghourSewing;
    }
    public Integer getMonthlyTotalRunningMc() {
        return this.monthlyTotalRunningMc;
    }
    
    public void setMonthlyTotalRunningMc(Integer monthlyTotalRunningMc) {
        this.monthlyTotalRunningMc = monthlyTotalRunningMc;
    }
    public Integer getMonthlyAverageRunningMc() {
        return this.monthlyAverageRunningMc;
    }
    
    public void setMonthlyAverageRunningMc(Integer monthlyAverageRunningMc) {
        this.monthlyAverageRunningMc = monthlyAverageRunningMc;
    }
    public Integer getFactoryTotalMc() {
        return this.factoryTotalMc;
    }
    
    public void setFactoryTotalMc(Integer factoryTotalMc) {
        this.factoryTotalMc = factoryTotalMc;
    }
    public Integer getSewingOperatorPresent() {
        return this.sewingOperatorPresent;
    }
    
    public void setSewingOperatorPresent(Integer sewingOperatorPresent) {
        this.sewingOperatorPresent = sewingOperatorPresent;
    }
    public Integer getSewingHelperPresent() {
        return this.sewingHelperPresent;
    }
    
    public void setSewingHelperPresent(Integer sewingHelperPresent) {
        this.sewingHelperPresent = sewingHelperPresent;
    }
    public Integer getSewingOperatorHelperPresent() {
        return this.sewingOperatorHelperPresent;
    }
    
    public void setSewingOperatorHelperPresent(Integer sewingOperatorHelperPresent) {
        this.sewingOperatorHelperPresent = sewingOperatorHelperPresent;
    }
    public Integer getTotalNoOfManHourAvilableMohel() {
        return this.totalNoOfManHourAvilableMohel;
    }
    
    public void setTotalNoOfManHourAvilableMohel(Integer totalNoOfManHourAvilableMohel) {
        this.totalNoOfManHourAvilableMohel = totalNoOfManHourAvilableMohel;
    }




}


